http:
  middlewares:
    # Single Sign On
    auth:
      forwardAuth:
        address: "http://auth:9091/api/verify?rd=https://auth.%DOMAIN_NAME%/"
        trustForwardHeader: true
        authResponseHeaders:
          - "Remote-User"
          - "Remote-Groups"

    # Allow IFrames from root domain and any subdomain
    allowFrames:
      headers:
        contentSecurityPolicy: frame-ancestors 'self' %DOMAIN_NAME% *.%DOMAIN_NAME%
        stsIncludeSubdomains: true
        frameDeny: false

    # Enforce secure headers
    # Not used. I need to find a way to apply this middleware to all routers without having to specify it to all routers one by one
    securityHeaders:
      headers:
        accessControlAllowMethods: ["GET", "OPTIONS", "PUT"]
        accessControlMaxAge: 100
        hostsProxyHeaders: ["X-Forwarded-Host"]
        sslRedirect: true
        stsSeconds: 63072000 # Two years
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "same-origin"
        featurePolicy: "camera 'none'; geolocation 'none'; microphone 'none'; payment 'none'; usb 'none';"
        customResponseHeaders:
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex,"
          server: ""
