http:
  middlewares:
    # Single Sign On
    auth:
      forwardAuth:
        address: "http://auth:9091/api/verify?rd=https://auth.%DOMAIN_NAME%/"
        trustForwardHeader: true
        authResponseHeaders:
          - "Remote-User"
          - "Remote-Groups"

    # Allow IFrames from root domain and any subdomain
    allowFrames:
      headers:
        contentSecurityPolicy: frame-ancestors 'self' %DOMAIN_NAME% *.%DOMAIN_NAME%
        stsIncludeSubdomains: true
        frameDeny: false

