http:
  middlewares:
    auth:
      forwardAuth:
        address: "http://auth:9091/api/verify?rd=https://auth.%DOMAIN_NAME%/"
        trustForwardHeader: true
        uthResponseHeaders:
          - "Remote-User"
          - "Remote-Groups"
