log:
  level: INFO

accessLog:
  filePath: "/var/log/access.log"
  format: json
  filters:
    statusCodes:
      - "400-499"
  fields:
    defaultMode: keep
    headers:
      defaultMode: keep
      names:
        CF-Connecting-IP: keep



entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      tls:
        certresolver: "cloudflare"
        domains:
          - main: "%DOMAIN_NAME%"
            sans: ["*.%DOMAIN_NAME%"]


api:
  dashboard: true

certificatesResolvers:
  cloudflare:
    acme:
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0
      email: "%LETS_ENCRYPT_EMAIL%"
      storage: "acme.json"
      # Uncomment to use Let's Encrypt Staging (for testing only)
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory


providers:
  docker:
    network: "web"
    # Services without the label "traefik.enable=false" will be exposed
    exposedByDefault: true
    # Services without explicit router rule will be accessible at [SERVICE_NAME].[DOMAIN_NAME]
    defaultRule: 'Host(`{{ index .Labels "com.docker.compose.service" }}.%DOMAIN_NAME%`)'


  file:
    filename: /dynamic-conf.yml
    watch: true
