log:
  level: INFO

accessLog:
  filePath: "/var/log/access.log"
  format: json
  filters:
    statusCodes:
      - "400-499"
  fields:
    defaultMode: keep
    headers:
      defaultMode: keep
      names:
        CF-Connecting-IP: keep



entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

api:
  dashboard: true

certificatesResolvers:
  le:
    acme:
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0
      email: "%LETS_ENCRYPT_EMAIL%"
      storage: "acme.json"
      # Uncomment to use Let's Encrypt Staging (for testing only)
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory


providers:
  docker:
    exposedByDefault: false
  file:
    filename: /dynamic-conf.yml
    watch: true
