###############################################################
#                   Authelia configuration                    #
###############################################################

host: 0.0.0.0
port: 9091
log_level: debug
default_redirection_url: https://%DOMAIN_NAME%
totp:
  issuer: authelia.com

authentication_backend:
  ldap:
    url: ldap://ldap
    skip_verify: false
    # TODO: replace with dynamic splitting of ${DOMAIN_NAME}
    base_dn: dc=EXAMPLE,dc=TLD

    username_attribute: uid

    additional_users_dn: ou=users

    users_filter: (&({username_attribute}={input})(objectClass=person))

    additional_groups_dn: ou=groups

    groups_filter: (&(member={dn})(objectclass=groupOfNames))

    group_name_attribute: cn

    mail_attribute: mail

    # The username and password of the admin user.
    # TODO: replace with dynamic username and domain name
    user: cn=ADMIN,dc=EXAMPLE,dc=TLD
    # Use a docker secret
    password: ADMINPWD

access_control:
  default_policy: deny
  rules:
    - domain: "*.%DOMAIN_NAME%"
      policy: one_factor

session:
  name: authelia_session
  secret: unsecure_session_secret
  expiration: 3600 # 1 hour
  inactivity: 300 # 5 minutes
  domain: %DOMAIN_NAME%

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  local:
    path: /var/lib/authelia/db.sqlite3

notifier:
  filesystem:
    filename: /var/lib/authelia/notification.txt
