###############################################################
#                         Users Database                      #
###############################################################

# This file can be used if you do not have an LDAP set up.

# List of users
users:
  %USERNAME%:
    password: "%HASHED_PWD%"
    email: xxx@xx.xx
    groups:
      - admins
      - users
