#! /bin/bash


# Prevent sudo timeout
sudo -v
while true; do
  sudo -nv; sleep 1m
  kill -0 $$ 2>/dev/null || exit   # Exit when the parent process is not running any more
done &


echo "Mounting drives..."
if manage-disks -m ;
then
  echo "Mounting drives succeeded"
else
  echo "Mounting drives failed"
  exit 1
fi

systemctl start server-apps-suite.service
