#! /bin/bash


# Prevent sudo timeout
sudo -v
while true; do
  sudo -nv; sleep 1m
  kill -0 $$ 2>/dev/null || exit   # Exit when the parent process is not running any more
done &


# Start services that depend on config dirs located on mounted drives after these drives are mounted
# Start a service
# $1: Service name
function start_service() {
  printf "Starting $1... "
  sudo systemctl start $1
  printf "Done !\n"
}

echo "Mounting drives..."
if manage-disks -m ;
then
  echo "Mounting drives succeeded"
else
  echo "Mounting drives failed"
  exit 1
fi

start_service transmission
start_service nginx
start_service kodi
start_service jackett
start_service sonarr
start_service radarr
