#-------------------------------------------------
# Configure VPN
#-------------------------------------------------


${INSTALL} openvpn
# Auto generate OpenVPN config files for VPN Private Internet Access (pia)
    ${INSTALL} pia-tools
    sudo su -c "echo '${vpn_login}\n${vpn_password}' | pia-tools --setup"
# Block non-VPN traffic. Works in conjunction with ufw
    sudo pia-tools --disallow
# Enable OpenVPN, the config file is one of the config files generated by pia-tools
    sudo systemctl enable pia@France
# Update openVPN config files
    sudo systemctl start pia-tools-update.timer
# Custom service to stop transmission when connection to the VPN is lost
sudo su -c "echo '[Unit]
Description=VPN connection check
[Service]
Type=oneshot
ExecStart=/usr/bin/pia-tools --check' > /etc/systemd/system/pia-tools-check.service"
sudo su -c "echo '[Unit]
Description=Recurrent VPN connection check
[Timer]
OnCalendar=*:0/1
Persistent=true
[Install]
WantedBy=timers.target' > /etc/systemd/system/pia-tools-check.timer"
    sudo systemctl enable pia-tools-check.timer
