#-------------------------------------------------
# Configure VPN
#-------------------------------------------------


${INSTALL} openvpn
# Auto generate OpenVPN config files for VPN Private Internet Access (pia)
    ${INSTALL} fakeroot  # Is required by pia to install, but not listed as a dependency
    ${INSTALL} private-internet-access-vpn
    # Write credentials in a file
        vpn_credentials_file="/etc/private-internet-access/login.conf"
        sudo su -c "echo ${vpn_login} > ${vpn_credentials_file}"
        sudo su -c "echo ${vpn_password} >> ${vpn_credentials_file}"
        sudo chown root:root ${vpn_credentials_file}
        sudo chmod 0600 ${vpn_credentials_file}
    # Create OpenVPN config files for pia
        sudo pia -a
    # Reaload systemd unit files, so that OpenVPN can detect files generated by pia
        sudo systemctl daemon-reload
# Enable OpenVPN, the config file is one of the config files generated by pia
    sudo systemctl enable openvpn-client@France

