  # System monitoring tool
  glances:
    image: "easypi/glances-arm"
    container_name: "glances"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "%GLANCES_PORT%:61208"
    restart: always
    environment:
      - GLANCES_OPT=-w
    pid: host
