  # Torrent trackers proxy
  jackett:
    image: "lsioarmhf/jackett"
    container_name: "jackett"
    volumes:
      - %CONTAINERS_CONFIG_DIR%/jackett:/config
      - %TORRENTS_BLACKHOLE%:/downloads
      - "/etc/localtime:/etc/localtime:ro"
      - %DOCKER_SHARED_DIR%:/shared
    ports:
      - "%JACKETT_PORT%:9117"
    restart: always
    environment:
      - PUID=%DOCKER_USER_ID%
      - PGID=%DOCKER_GROUP_ID%
      - TZ=%TIMEZONE%
