  # Quickly access all the services in one spot
  organizr:
    container_name: organizr
    restart: always
    image: lsioarmhf/organizr
    volumes:
      - %CONTAINERS_CONFIG_DIR%/organizr:/config
      - %DOCKER_SHARED_DIR%:/shared
    ports:
      - "%ORGANIZR_PORT%:80"
    environment:
      - PUID=%DOCKER_USER_ID%
      - PGID=%DOCKER_GROUP_ID%
      - TZ=%TIMEZONE%
