  plexms:
    container_name: plexms
    restart: always
    image: plexinc/pms-docker
    volumes:
      - %CONTAINERS_CONFIG_DIR%/plexms:/config
      - %USER_DIR%/Downloads/plex_tmp:/transcode
      - %MEDIA_DIR%:/media
      - %DOCKER_SHARED_DIR%:/shared
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    environment:
      - TZ=%TIMEZONE%
      - HOSTNAME="Docker Plex"
      - PLEX_CLAIM="claim-YYYYYYYYY"
      - PLEX_UID=%DOCKER_USER_ID%
      - PLEX_GID=%DOCKER_GROUP_ID%
      - ADVERTISE_IP="http://SERVER-IP:32400/"
