  # Movies PVR
  radarr:
    image: "lsioarmhf/radarr"
    container_name: "radarr"
    volumes:
      - %CONTAINERS_CONFIG_DIR%/radarr:/config
      - %DOWNLOADS_COMPLETE_DIR%:/downloads
      - %MOVIES_DIR%:/movies
      - "/etc/localtime:/etc/localtime:ro"
      - %DOCKER_SHARED_DIR%:/shared
    ports:
      - "%RADARR_PORT%:7878"
    restart: always
    environment:
      - PUID=%DOCKER_USER_ID%
      - PGID=%DOCKER_GROUP_ID%
      - TZ=%TIMEZONE%
