version: "2"
services:
  # VPN
  pia:
    image: qmcgaw/private-internet-access
    container_name: pia
    cap_add:
        - NET_ADMIN
    devices:
        - /dev/net/tun
    networks:
        - pianet
    volumes:
        - /tmp/auth.conf:/auth.conf:ro
    environment:
        - PROTOCOL=tcp
        - ENCRYPTION=strong
        - REGION=France
    restart: always
    pianet:
        external: true
