  # Reverse proxy
  traefik:
    hostname: traefik
    image: traefik:latest
    container_name: traefik
    restart: always
    domainname: %DOMAIN_NAME%
    networks:
      - default
      - traefik_proxy
      - vpn_client_net
    ports:
      - "80:80"
      - "443:443"
      # - "XXXX:8080"
    environment:
      - CLOUDFLARE_EMAIL=%CLOUDFLARE_EMAIL%
      - CLOUDFLARE_API_KEY=%CLOUDFLARE_API_KEY%
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.frontend.rule=Host:traefik.%DOMAIN_NAME%"
      - "traefik.port=8080"
      - "traefik.docker.network=traefik_proxy"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - %CONTAINERS_DATA_DIR%/traefik:/etc/traefik
