  # Reverse proxy
  traefik:
    container_name: traefik
    image: traefik:2.2.1
    restart: unless-stopped
    networks:
      - web
    domainname: %DOMAIN_NAME%
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - %CONTAINERS_CONFIG_DIR%/traefik/traefik.yml:/traefik.yml
      - %CONTAINERS_CONFIG_DIR%/traefik/dynamic-conf.yml:/dynamic-conf.yml
      - %CONTAINERS_DATA_DIR%/traefik/acme.json:/acme.json
      - /var/log/traefik:/var/log   # Used by Fail2ban
      - /var/run/docker.sock:/var/run/docker.sock:ro
    secrets:
      - traefik_cf_api_key
    environment:
      - CF_API_EMAIL=%CLOUDFLARE_EMAIL%
      - CF_API_KEY_FILE=/run/secrets/traefik_cf_api_key
    labels:
      - traefik.http.routers.traefik.middlewares=auth@file
      - traefik.http.routers.traefik.service=api@internal
