#!/usr/bin/python
# Script to randomly set background from wallpapers subreddit. Schedule with cron.
# Run "crontab -e" then add an entry such as "*/5 * * * * /home/jake/wscript.py"
# Contributions are welcome. Do what ever you want with this script, but I am
# not responsible for it.

import json
import urllib.request
import random
import shutil
import os

#Settings
subreddits = ['http://www.reddit.com/r/earthporn/.json']
img_file = ['/tmp/reddit_wallpaper.jpg']
temp_suffix = '_temp'
img_exts = ['jpg','png']
hide_over_18 = False
#End Settings

img_urls = []



def getimg(post):
    return post['data']['url']



def check_ext(img_url):
    for ext in img_exts:
        if img_url.endswith(ext):
            return True
    return False



def not_over_18(post):
    return not post['data']['over_18']



for subreddit in subreddits:
    f = urllib.request.urlopen(subreddit)
    raw_json = bytes.decode(f.read())
    json_obj = json.loads(raw_json)
    posts = json_obj['data']['children']
    if hide_over_18:
        posts = list(filter(not_over_18,posts))
    img_urls += list(filter(check_ext,list(map(getimg,posts))))
rand_urls = random.sample(img_urls,len(img_file))



#Done in two steps to hide downloading on slow connections
for rand_url, img_file in zip(rand_urls, img_file):
    urllib.request.urlretrieve(rand_url, img_file+temp_suffix)
    shutil.move(img_file+temp_suffix,img_file)




cmd = '/bin/feh --bg-scale ' + img_file
os.system(cmd)
