#!/bin/bash


# Start daemons and tray icons


#----- Daemons
    # Auto USB mounter
        /usr/bin/udiskie -s &
    # Disale touchpad while typing on keyboard
        syndaemon -i 0.5 -d &
    # Start pulseaudio
        pulseaudio --start
    # Notifications daemon
        dunst &

#----- Tray icons
    # Network manager with tray icon
        nm-applet 2>&1 /dev/null &
    # Pulse audi tray icon
        pasystray &

