  # Manage docker conainers via a web UI
  portainer:
    image: kmlucy/docker-proxy-acl
    container_name: docker-proxy-acl
    restart: always
    environment:
      - "OPTIONS=-a containers"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - %DOCKER_SHARED_DIR%/docker-proxy-acl:/tmp/docker-proxy-acl
