  # Manage docker conainers via a web UI
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    command: --templates http://templates/templates.json
    ports:
      - "%PORTAINER_PORT%:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - %CONTAINERS_CONFIG_DIR%/portainer/data:/data
      - %DOCKER_SHARED_DIR%:/shared
    environment:
      - TZ=%TIMEZONE%
