  # Docker conainers admin interface
  portainer:
    container_name: portainer
    image: portainer/portainer:1.22.0
    restart: unless-stopped
    networks:
      - web
    command: --no-auth
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - %SERVICES_DATA_DIR%/portainer/data:/data
    environment:
      - TZ=%TIMEZONE%
    labels:
      - traefik.http.routers.portainer.middlewares=auth@file
      - traefik.http.services.portainer.loadbalancer.server.port=9000
