  # Auto-update docker containers (pulls latest image and restart container)
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:0.3.11
    restart: unless-stopped
    networks:
      - notifications
    command: --cleanup --label-enable --interval 3600
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=%TIMEZONE%
      - WATCHTOWER_NOTIFICATIONS=gotify
      - WATCHTOWER_NOTIFICATION_GOTIFY_URL=http://gotify:80
      - WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN=%GOTIFY_WATCHTOWER_API_TOKEN%
    labels:
      - traefik.enable=false
